version: '3'

services:
  db:
    image: postgres
    container_name: dbpostgres
    restart: unless-stopped
    tty: true
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nestauth

volumes:
  pgdata:
